### ISSUE TITLE
HU03 - TASK03 - navegacion detalle de artista

### ISSUE THREAD

**Issue by ccpinzonh1** [Santiago9913/MISW4203-Moviles#18]
#3  HU03

Implementar la navegación desde la lista de artistas a la pantalla de detalle del artista al hacer clic en "Ver detalle".

**Comment by Santiago9913** [comment]
La pantalla a la que se navega es una pantalla con solo texto, debido a que la implementación del detalle esta para futuros sprints (#4)

**Comment by Santiago9913** [comment]
Adicionalmente se debe tener en cuenta el escenario de prueba para este flujo
